# action.yml
name: 'Build and Publish TechDocs'
description: 'Build and Publish TechDocs to DevHub'
inputs:
    operation:  # id of input
        description: 'The operation to perform - either "build" or "publish"'
        required: true
        default: 'build'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.operation }}
