# action.yml
name: 'Build and Publish TechDocs'
description: 'Build and Publish TechDocs to DevHub'
inputs:
    publish:  # id of input
        description: 'Flag to control whether generated documentation is published to shared bucket or not.'
        required: true
        default: 'false'
runs:
    using: 'docker'
    image: 'ghcr.io/bcgov/devhub-techdocs-publish'
    args:
        - ${{ inputs.publish }}
