site_name: "DevHub TechDocs Publishing Action"
site_description: "A guide to using the DevHub TechDocs Publishing Action."
repo_url: https://github.com/bcgov/devhub-techdocs-publish
plugins:
    - techdocs-core
    - ezlinks

markdown_extensions:
    - md_in_html
    -   mkpatcher:
            location: patcher.py
