name: Test DevHub TechDocs Publish Action

on: workflow_dispatch

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to build and publish techdocs content
        steps:
            # To use this repository's private action,
            # you must check out the repository
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build TechDocs
              uses: ./ # Uses an action in the root directory
              id: build
              with:
                  operation: 'build'
