name: Test DevHub TechDocs Publish Action

on: workflow_dispatch

jobs:
    test_techdocs_build_job:
        runs-on: ubuntu-latest
        env:
            TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
            TECHDOCS_S3_DEV_ROOT_PATH: ${{ vars.TECHDOCS_S3_DEV_ROOT_PATH }}
            AWS_ACCESS_KEY_ID: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.TECHDOCS_AWS_REGION }}
            AWS_ENDPOINT: ${{ secrets.TECHDOCS_AWS_ENDPOINT }}
            ENTITY_NAMESPACE: ${{ vars.TECHDOCS_ENTITY_NAMESPACE }}
        name: A job to build and publish techdocs content
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build TechDocs
              uses: ./ # Uses the action in the root directory
              id: build_and_publish
              with:
                  publish: 'true'
